services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - db_data:/app/data/db
      - slides:/app/data/slides
    environment:
      - GOOGLE_ID_TOKEN=
      - COOKIE_SECRET_KEY= 
      - COOKIE_SECURE=false
      - DATABASE_URL=sqlite:///app/data/db/konsol.db
      - SLIDE_IMAGE_DIR=/app/data/slides

  web:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped

  nginx:
    image: nginx:latest
    volumes:
      - ./outer-nginx.conf:/etc/nginx/conf.d/app.conf:ro
    ports:
      - "80:80"
    depends_on:
      - web
      - backend
    restart: unless-stopped

volumes:
  db_data:
  slides: